spring.application.name=scraper-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/pricetracker_scraper_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

scraper.fixed-delay-ms=86400000
scraper.initial-delay-ms=30000

scraper.demo-products[0].productId=1
scraper.demo-products[0].shopName=Alza
scraper.demo-products[0].url=https://alza.cz/ps5-pro

services.internal.token=pt-internal-secret-2026
services.catalog.base-url=http://localhost:8082
