services.user.base-url=http://user-service:8081
services.catalog.base-url=http://product-catalog-service:8082
services.scraper.base-url=http://scraper-service:8083
services.notification.base-url=http://notification-service:8084
